import type { ThemePreset } from "@/types/tokens";

export const PRESETS: ThemePreset[] = [
  {
    id: "default",
    name: "Default",
    description: "Clean neutral palette — the classic shadcn/ui look",
    tokens: {
      light: {
        background: "#ffffff",
        foreground: "#0a0a0a",
        card: "#ffffff",
        "card-foreground": "#0a0a0a",
        popover: "#ffffff",
        "popover-foreground": "#0a0a0a",
        primary: "#171717",
        "primary-foreground": "#fafafa",
        secondary: "#f5f5f5",
        "secondary-foreground": "#171717",
        muted: "#f5f5f5",
        "muted-foreground": "#737373",
        accent: "#f5f5f5",
        "accent-foreground": "#171717",
        destructive: "#dc2626",
        "destructive-foreground": "#fafafa",
        border: "#e5e5e5",
        input: "#e5e5e5",
        ring: "#0a0a0a",
        "chart-1": "#3b82f6",
        "chart-2": "#8b5cf6",
        "chart-3": "#10b981",
        "chart-4": "#f59e0b",
        "chart-5": "#f43f5e",
        sidebar: "#fafafa",
        "sidebar-foreground": "#0a0a0a",
        "sidebar-primary": "#171717",
        "sidebar-primary-foreground": "#fafafa",
        "sidebar-accent": "#f5f5f5",
        "sidebar-accent-foreground": "#171717",
        "sidebar-border": "#e5e5e5",
        "sidebar-ring": "#0a0a0a",
      },
      dark: {
        background: "#0a0a0a",
        foreground: "#fafafa",
        card: "#171717",
        "card-foreground": "#fafafa",
        popover: "#171717",
        "popover-foreground": "#fafafa",
        primary: "#fafafa",
        "primary-foreground": "#171717",
        secondary: "#262626",
        "secondary-foreground": "#fafafa",
        muted: "#262626",
        "muted-foreground": "#a3a3a3",
        accent: "#262626",
        "accent-foreground": "#fafafa",
        destructive: "#ef4444",
        "destructive-foreground": "#fafafa",
        border: "#262626",
        input: "#262626",
        ring: "#d4d4d4",
        "chart-1": "#60a5fa",
        "chart-2": "#a78bfa",
        "chart-3": "#34d399",
        "chart-4": "#fbbf24",
        "chart-5": "#fb7185",
        sidebar: "#171717",
        "sidebar-foreground": "#fafafa",
        "sidebar-primary": "#fafafa",
        "sidebar-primary-foreground": "#171717",
        "sidebar-accent": "#262626",
        "sidebar-accent-foreground": "#fafafa",
        "sidebar-border": "#262626",
        "sidebar-ring": "#d4d4d4",
      },
      borderRadius: "0.5rem",
      fontFamily: {
        sans: "Inter, ui-sans-serif, system-ui, sans-serif",
        serif: "Georgia, ui-serif, serif",
        mono: "JetBrains Mono, ui-monospace, monospace",
      },
    },
  },

  {
    id: "ocean",
    name: "Ocean",
    description: "Cool blues and teals inspired by deep water",
    tokens: {
      light: {
        background: "#f0f9ff",
        foreground: "#0c2340",
        card: "#ffffff",
        "card-foreground": "#0c2340",
        popover: "#ffffff",
        "popover-foreground": "#0c2340",
        primary: "#0369a1",
        "primary-foreground": "#f0f9ff",
        secondary: "#e0f2fe",
        "secondary-foreground": "#0c2340",
        muted: "#e0f2fe",
        "muted-foreground": "#0e6693",
        accent: "#bae6fd",
        "accent-foreground": "#0c2340",
        destructive: "#dc2626",
        "destructive-foreground": "#ffffff",
        border: "#bae6fd",
        input: "#bae6fd",
        ring: "#0369a1",
        "chart-1": "#0369a1",
        "chart-2": "#0891b2",
        "chart-3": "#0d9488",
        "chart-4": "#7c3aed",
        "chart-5": "#e11d48",
        sidebar: "#e0f2fe",
        "sidebar-foreground": "#0c2340",
        "sidebar-primary": "#0369a1",
        "sidebar-primary-foreground": "#f0f9ff",
        "sidebar-accent": "#bae6fd",
        "sidebar-accent-foreground": "#0c2340",
        "sidebar-border": "#bae6fd",
        "sidebar-ring": "#0369a1",
      },
      dark: {
        background: "#0c1a2e",
        foreground: "#e0f2fe",
        card: "#0f2744",
        "card-foreground": "#e0f2fe",
        popover: "#0f2744",
        "popover-foreground": "#e0f2fe",
        primary: "#38bdf8",
        "primary-foreground": "#0c1a2e",
        secondary: "#164e63",
        "secondary-foreground": "#e0f2fe",
        muted: "#164e63",
        "muted-foreground": "#67e8f9",
        accent: "#0e7490",
        "accent-foreground": "#e0f2fe",
        destructive: "#ef4444",
        "destructive-foreground": "#fafafa",
        border: "#164e63",
        input: "#164e63",
        ring: "#38bdf8",
        "chart-1": "#38bdf8",
        "chart-2": "#22d3ee",
        "chart-3": "#2dd4bf",
        "chart-4": "#a78bfa",
        "chart-5": "#fb7185",
        sidebar: "#0f2744",
        "sidebar-foreground": "#e0f2fe",
        "sidebar-primary": "#38bdf8",
        "sidebar-primary-foreground": "#0c1a2e",
        "sidebar-accent": "#164e63",
        "sidebar-accent-foreground": "#e0f2fe",
        "sidebar-border": "#164e63",
        "sidebar-ring": "#38bdf8",
      },
      borderRadius: "0.75rem",
      fontFamily: {
        sans: "Inter, ui-sans-serif, system-ui, sans-serif",
        serif: "Georgia, ui-serif, serif",
        mono: "JetBrains Mono, ui-monospace, monospace",
      },
    },
  },

  {
    id: "forest",
    name: "Forest",
    description: "Earthy greens and warm neutrals",
    tokens: {
      light: {
        background: "#f0fdf4",
        foreground: "#14532d",
        card: "#ffffff",
        "card-foreground": "#14532d",
        popover: "#ffffff",
        "popover-foreground": "#14532d",
        primary: "#15803d",
        "primary-foreground": "#f0fdf4",
        secondary: "#dcfce7",
        "secondary-foreground": "#14532d",
        muted: "#dcfce7",
        "muted-foreground": "#166534",
        accent: "#bbf7d0",
        "accent-foreground": "#14532d",
        destructive: "#dc2626",
        "destructive-foreground": "#ffffff",
        border: "#bbf7d0",
        input: "#bbf7d0",
        ring: "#15803d",
        "chart-1": "#15803d",
        "chart-2": "#0d9488",
        "chart-3": "#ca8a04",
        "chart-4": "#2563eb",
        "chart-5": "#dc2626",
        sidebar: "#dcfce7",
        "sidebar-foreground": "#14532d",
        "sidebar-primary": "#15803d",
        "sidebar-primary-foreground": "#f0fdf4",
        "sidebar-accent": "#bbf7d0",
        "sidebar-accent-foreground": "#14532d",
        "sidebar-border": "#bbf7d0",
        "sidebar-ring": "#15803d",
      },
      dark: {
        background: "#052e16",
        foreground: "#dcfce7",
        card: "#14532d",
        "card-foreground": "#dcfce7",
        popover: "#14532d",
        "popover-foreground": "#dcfce7",
        primary: "#4ade80",
        "primary-foreground": "#052e16",
        secondary: "#166534",
        "secondary-foreground": "#dcfce7",
        muted: "#166534",
        "muted-foreground": "#86efac",
        accent: "#166534",
        "accent-foreground": "#dcfce7",
        destructive: "#ef4444",
        "destructive-foreground": "#fafafa",
        border: "#166534",
        input: "#166534",
        ring: "#4ade80",
        "chart-1": "#4ade80",
        "chart-2": "#2dd4bf",
        "chart-3": "#facc15",
        "chart-4": "#60a5fa",
        "chart-5": "#f87171",
        sidebar: "#14532d",
        "sidebar-foreground": "#dcfce7",
        "sidebar-primary": "#4ade80",
        "sidebar-primary-foreground": "#052e16",
        "sidebar-accent": "#166534",
        "sidebar-accent-foreground": "#dcfce7",
        "sidebar-border": "#166534",
        "sidebar-ring": "#4ade80",
      },
      borderRadius: "0.375rem",
      fontFamily: {
        sans: "Inter, ui-sans-serif, system-ui, sans-serif",
        serif: "Georgia, ui-serif, serif",
        mono: "JetBrains Mono, ui-monospace, monospace",
      },
    },
  },

  {
    id: "rose",
    name: "Rose",
    description: "Warm pinks and soft magentas",
    tokens: {
      light: {
        background: "#fff1f2",
        foreground: "#4c0519",
        card: "#ffffff",
        "card-foreground": "#4c0519",
        popover: "#ffffff",
        "popover-foreground": "#4c0519",
        primary: "#e11d48",
        "primary-foreground": "#fff1f2",
        secondary: "#ffe4e6",
        "secondary-foreground": "#4c0519",
        muted: "#ffe4e6",
        "muted-foreground": "#9f1239",
        accent: "#fecdd3",
        "accent-foreground": "#4c0519",
        destructive: "#be123c",
        "destructive-foreground": "#ffffff",
        border: "#fecdd3",
        input: "#fecdd3",
        ring: "#e11d48",
        "chart-1": "#e11d48",
        "chart-2": "#db2777",
        "chart-3": "#9333ea",
        "chart-4": "#2563eb",
        "chart-5": "#d97706",
        sidebar: "#ffe4e6",
        "sidebar-foreground": "#4c0519",
        "sidebar-primary": "#e11d48",
        "sidebar-primary-foreground": "#fff1f2",
        "sidebar-accent": "#fecdd3",
        "sidebar-accent-foreground": "#4c0519",
        "sidebar-border": "#fecdd3",
        "sidebar-ring": "#e11d48",
      },
      dark: {
        background: "#1c0209",
        foreground: "#ffe4e6",
        card: "#4c0519",
        "card-foreground": "#ffe4e6",
        popover: "#4c0519",
        "popover-foreground": "#ffe4e6",
        primary: "#fb7185",
        "primary-foreground": "#1c0209",
        secondary: "#881337",
        "secondary-foreground": "#ffe4e6",
        muted: "#881337",
        "muted-foreground": "#fda4af",
        accent: "#9f1239",
        "accent-foreground": "#ffe4e6",
        destructive: "#f43f5e",
        "destructive-foreground": "#fafafa",
        border: "#881337",
        input: "#881337",
        ring: "#fb7185",
        "chart-1": "#fb7185",
        "chart-2": "#f472b6",
        "chart-3": "#c084fc",
        "chart-4": "#60a5fa",
        "chart-5": "#fbbf24",
        sidebar: "#4c0519",
        "sidebar-foreground": "#ffe4e6",
        "sidebar-primary": "#fb7185",
        "sidebar-primary-foreground": "#1c0209",
        "sidebar-accent": "#881337",
        "sidebar-accent-foreground": "#ffe4e6",
        "sidebar-border": "#881337",
        "sidebar-ring": "#fb7185",
      },
      borderRadius: "1rem",
      fontFamily: {
        sans: "Inter, ui-sans-serif, system-ui, sans-serif",
        serif: "Georgia, ui-serif, serif",
        mono: "JetBrains Mono, ui-monospace, monospace",
      },
    },
  },

  {
    id: "midnight",
    name: "Midnight",
    description: "Deep purples with vibrant accents — great for creative tools",
    tokens: {
      light: {
        background: "#faf5ff",
        foreground: "#2e1065",
        card: "#ffffff",
        "card-foreground": "#2e1065",
        popover: "#ffffff",
        "popover-foreground": "#2e1065",
        primary: "#7c3aed",
        "primary-foreground": "#faf5ff",
        secondary: "#ede9fe",
        "secondary-foreground": "#2e1065",
        muted: "#ede9fe",
        "muted-foreground": "#6d28d9",
        accent: "#ddd6fe",
        "accent-foreground": "#2e1065",
        destructive: "#dc2626",
        "destructive-foreground": "#ffffff",
        border: "#ddd6fe",
        input: "#ddd6fe",
        ring: "#7c3aed",
        "chart-1": "#7c3aed",
        "chart-2": "#4f46e5",
        "chart-3": "#2563eb",
        "chart-4": "#0891b2",
        "chart-5": "#e11d48",
        sidebar: "#ede9fe",
        "sidebar-foreground": "#2e1065",
        "sidebar-primary": "#7c3aed",
        "sidebar-primary-foreground": "#faf5ff",
        "sidebar-accent": "#ddd6fe",
        "sidebar-accent-foreground": "#2e1065",
        "sidebar-border": "#ddd6fe",
        "sidebar-ring": "#7c3aed",
      },
      dark: {
        background: "#0d0820",
        foreground: "#ede9fe",
        card: "#1e1035",
        "card-foreground": "#ede9fe",
        popover: "#1e1035",
        "popover-foreground": "#ede9fe",
        primary: "#a78bfa",
        "primary-foreground": "#0d0820",
        secondary: "#2e1065",
        "secondary-foreground": "#ede9fe",
        muted: "#2e1065",
        "muted-foreground": "#c4b5fd",
        accent: "#4c1d95",
        "accent-foreground": "#ede9fe",
        destructive: "#ef4444",
        "destructive-foreground": "#fafafa",
        border: "#2e1065",
        input: "#2e1065",
        ring: "#a78bfa",
        "chart-1": "#a78bfa",
        "chart-2": "#818cf8",
        "chart-3": "#60a5fa",
        "chart-4": "#22d3ee",
        "chart-5": "#fb7185",
        sidebar: "#1e1035",
        "sidebar-foreground": "#ede9fe",
        "sidebar-primary": "#a78bfa",
        "sidebar-primary-foreground": "#0d0820",
        "sidebar-accent": "#2e1065",
        "sidebar-accent-foreground": "#ede9fe",
        "sidebar-border": "#2e1065",
        "sidebar-ring": "#a78bfa",
      },
      borderRadius: "0.5rem",
      fontFamily: {
        sans: "Inter, ui-sans-serif, system-ui, sans-serif",
        serif: "Georgia, ui-serif, serif",
        mono: "JetBrains Mono, ui-monospace, monospace",
      },
    },
  },

  {
    id: "amber",
    name: "Amber",
    description: "Warm golden tones with an energetic feel",
    tokens: {
      light: {
        background: "#fffbeb",
        foreground: "#451a03",
        card: "#ffffff",
        "card-foreground": "#451a03",
        popover: "#ffffff",
        "popover-foreground": "#451a03",
        primary: "#d97706",
        "primary-foreground": "#fffbeb",
        secondary: "#fef3c7",
        "secondary-foreground": "#451a03",
        muted: "#fef3c7",
        "muted-foreground": "#92400e",
        accent: "#fde68a",
        "accent-foreground": "#451a03",
        destructive: "#dc2626",
        "destructive-foreground": "#ffffff",
        border: "#fde68a",
        input: "#fde68a",
        ring: "#d97706",
        "chart-1": "#d97706",
        "chart-2": "#ea580c",
        "chart-3": "#16a34a",
        "chart-4": "#2563eb",
        "chart-5": "#db2777",
        sidebar: "#fef3c7",
        "sidebar-foreground": "#451a03",
        "sidebar-primary": "#d97706",
        "sidebar-primary-foreground": "#fffbeb",
        "sidebar-accent": "#fde68a",
        "sidebar-accent-foreground": "#451a03",
        "sidebar-border": "#fde68a",
        "sidebar-ring": "#d97706",
      },
      dark: {
        background: "#1c0a00",
        foreground: "#fef3c7",
        card: "#451a03",
        "card-foreground": "#fef3c7",
        popover: "#451a03",
        "popover-foreground": "#fef3c7",
        primary: "#fbbf24",
        "primary-foreground": "#1c0a00",
        secondary: "#78350f",
        "secondary-foreground": "#fef3c7",
        muted: "#78350f",
        "muted-foreground": "#fcd34d",
        accent: "#92400e",
        "accent-foreground": "#fef3c7",
        destructive: "#ef4444",
        "destructive-foreground": "#fafafa",
        border: "#78350f",
        input: "#78350f",
        ring: "#fbbf24",
        "chart-1": "#fbbf24",
        "chart-2": "#fb923c",
        "chart-3": "#4ade80",
        "chart-4": "#60a5fa",
        "chart-5": "#f472b6",
        sidebar: "#451a03",
        "sidebar-foreground": "#fef3c7",
        "sidebar-primary": "#fbbf24",
        "sidebar-primary-foreground": "#1c0a00",
        "sidebar-accent": "#78350f",
        "sidebar-accent-foreground": "#fef3c7",
        "sidebar-border": "#78350f",
        "sidebar-ring": "#fbbf24",
      },
      borderRadius: "0.5rem",
      fontFamily: {
        sans: "Inter, ui-sans-serif, system-ui, sans-serif",
        serif: "Georgia, ui-serif, serif",
        mono: "JetBrains Mono, ui-monospace, monospace",
      },
    },
  },
];

export const DEFAULT_PRESET = PRESETS[0];
