"use client";

import React, { useState } from "react";
import { useThemeStore } from "@/store/themeStore";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Check, Copy } from "lucide-react";
import { semanticTokensToCssVars } from "@/lib/token-utils";

interface ExportDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

function generateCssVars(tokens: ReturnType<typeof useThemeStore.getState>["tokens"]): string {
  const lightVars: Record<string, string> = {
    ...tokens.light,
    "--radius": tokens.borderRadius,
    "--font-sans": tokens.fontFamily.sans,
    "--font-serif": tokens.fontFamily.serif,
    "--font-mono": tokens.fontFamily.mono,
  };

  const lightSection = semanticTokensToCssVars(lightVars, ":root");
  const darkSection = semanticTokensToCssVars(tokens.dark as unknown as Record<string, string>, ".dark");

  return `/* Generated by BaseUI Tweak — W3C Design Tokens */\n\n${lightSection}\n\n${darkSection}`;
}

function generateW3CTokens(
  tokens: ReturnType<typeof useThemeStore.getState>["tokens"],
  themeName: string
): string {
  const tree: Record<string, unknown> = {
    $schema: "https://tr.designtokens.org/format/",
    $description: `${themeName} theme tokens`,
    color: {
      $description: "Semantic color tokens",
      light: {} as Record<string, unknown>,
      dark: {} as Record<string, unknown>,
    },
    borderRadius: {
      base: {
        $type: "dimension",
        $value: tokens.borderRadius,
        $description: "Default border radius",
      },
    },
    typography: {
      fontFamily: {
        sans: { $type: "fontFamily", $value: tokens.fontFamily.sans },
        serif: { $type: "fontFamily", $value: tokens.fontFamily.serif },
        mono: { $type: "fontFamily", $value: tokens.fontFamily.mono },
      },
    },
  };

  for (const [key, value] of Object.entries(tokens.light)) {
    (tree.color as Record<string, unknown>).light = {
      ...((tree.color as Record<string, unknown>).light as Record<string, unknown>),
      [key]: { $type: "color", $value: value },
    };
  }
  for (const [key, value] of Object.entries(tokens.dark)) {
    (tree.color as Record<string, unknown>).dark = {
      ...((tree.color as Record<string, unknown>).dark as Record<string, unknown>),
      [key]: { $type: "color", $value: value },
    };
  }

  return JSON.stringify(tree, null, 2);
}

function generateTailwindConfig(
  tokens: ReturnType<typeof useThemeStore.getState>["tokens"]
): string {
  const lines = [
    `/** @type {import('tailwindcss').Config} */`,
    `module.exports = {`,
    `  darkMode: ["class"],`,
    `  theme: {`,
    `    extend: {`,
    `      colors: {`,
    `        background: "var(--background)",`,
    `        foreground: "var(--foreground)",`,
    `        primary: {`,
    `          DEFAULT: "var(--primary)",`,
    `          foreground: "var(--primary-foreground)",`,
    `        },`,
    `        secondary: {`,
    `          DEFAULT: "var(--secondary)",`,
    `          foreground: "var(--secondary-foreground)",`,
    `        },`,
    `        muted: {`,
    `          DEFAULT: "var(--muted)",`,
    `          foreground: "var(--muted-foreground)",`,
    `        },`,
    `        accent: {`,
    `          DEFAULT: "var(--accent)",`,
    `          foreground: "var(--accent-foreground)",`,
    `        },`,
    `        destructive: {`,
    `          DEFAULT: "var(--destructive)",`,
    `          foreground: "var(--destructive-foreground)",`,
    `        },`,
    `        card: {`,
    `          DEFAULT: "var(--card)",`,
    `          foreground: "var(--card-foreground)",`,
    `        },`,
    `        popover: {`,
    `          DEFAULT: "var(--popover)",`,
    `          foreground: "var(--popover-foreground)",`,
    `        },`,
    `        border: "var(--border)",`,
    `        input: "var(--input)",`,
    `        ring: "var(--ring)",`,
    `        sidebar: {`,
    `          DEFAULT: "var(--sidebar)",`,
    `          foreground: "var(--sidebar-foreground)",`,
    `          primary: "var(--sidebar-primary)",`,
    `          "primary-foreground": "var(--sidebar-primary-foreground)",`,
    `          accent: "var(--sidebar-accent)",`,
    `          "accent-foreground": "var(--sidebar-accent-foreground)",`,
    `          border: "var(--sidebar-border)",`,
    `          ring: "var(--sidebar-ring)",`,
    `        },`,
    `        "chart-1": "var(--chart-1)",`,
    `        "chart-2": "var(--chart-2)",`,
    `        "chart-3": "var(--chart-3)",`,
    `        "chart-4": "var(--chart-4)",`,
    `        "chart-5": "var(--chart-5)",`,
    `      },`,
    `      borderRadius: {`,
    `        DEFAULT: "var(--radius)",`,
    `        sm: "calc(var(--radius) - 4px)",`,
    `        lg: "calc(var(--radius) + 2px)",`,
    `        xl: "calc(var(--radius) + 4px)",`,
    `      },`,
    `      fontFamily: {`,
    `        sans: ["var(--font-sans)"],`,
    `        serif: ["var(--font-serif)"],`,
    `        mono: ["var(--font-mono)"],`,
    `      },`,
    `    },`,
    `  },`,
    `};`,
  ];
  return lines.join("\n");
}

export function ExportDialog({ open, onOpenChange }: ExportDialogProps) {
  const { tokens, themeName } = useThemeStore();
  const [copied, setCopied] = useState(false);
  const [activeTab, setActiveTab] = useState("css");

  const outputs: Record<string, string> = {
    css: generateCssVars(tokens),
    w3c: generateW3CTokens(tokens, themeName),
    tailwind: generateTailwindConfig(tokens),
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(outputs[activeTab]);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle>Export Theme</DialogTitle>
          <DialogDescription>
            Copy the generated code for your chosen format.
          </DialogDescription>
        </DialogHeader>

        <Tabs value={activeTab} onValueChange={setActiveTab}>
          <div className="flex items-center justify-between">
            <TabsList>
              <TabsTrigger value="css">CSS Variables</TabsTrigger>
              <TabsTrigger value="w3c">W3C Tokens</TabsTrigger>
              <TabsTrigger value="tailwind">Tailwind Config</TabsTrigger>
            </TabsList>
            <Button size="sm" variant="outline" onClick={handleCopy}>
              {copied ? (
                <><Check className="h-3.5 w-3.5 mr-1.5" /> Copied</>
              ) : (
                <><Copy className="h-3.5 w-3.5 mr-1.5" /> Copy</>
              )}
            </Button>
          </div>

          {(["css", "w3c", "tailwind"] as const).map((tab) => (
            <TabsContent key={tab} value={tab}>
              <pre className="max-h-96 overflow-auto rounded-[var(--radius)] bg-[var(--muted)] p-4 text-xs font-mono text-[var(--foreground)] whitespace-pre leading-relaxed">
                {outputs[tab]}
              </pre>
            </TabsContent>
          ))}
        </Tabs>
      </DialogContent>
    </Dialog>
  );
}
